language: R
sudo: required
cache: packages

r_packages:
  - bookdown

r_github_packages:
  - nulib/moderndive

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: nulib/moderndive_book
  on:
    branch: master
